### ISSUE TITLE
Anyone packaged RPM for CentOS 7?

### ISSUE THREAD

**Issue by elico** [haakonnessjoen/MAC-Telnet#36]
Anyone packaged RPM for CentOS 7?
There is a deb package for ubuntu and probably debian but I have not seen a CentOS package even for the client.

**Comment by elico** [comment]
OK so I have complied and packaged the tools for CentOS 7 but for some reason I am getting a segfault from the mactelnetd at runtime and I ran the service under gdb and the backtrace is:
```
#0  0x00007ffff78a4c8f in __strncpy_sse2_unaligned () from /lib64/libc.so.6
#1  0x0000000000402d03 in handle_packet (address=0x7fffffffc200, data_len=<optimized out>, data=0x7fffffffc710 "\001") at mactelnetd.c:731
#2  main (argc=<optimized out>, argv=<optimized out>) at mactelnetd.c:1145
```
I have used the latest 0.4.4.

This is the build output
```
+ ./autogen.sh
Copying file ABOUT-NLS
Copying file config.rpath
Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makevars.template
configure.ac:18: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:18: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:18: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:14: installing './compile'
configure.ac:18: installing './config.guess'
configure.ac:18: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
src/Makefile.am: installing './depcomp'
configure.ac:18: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:18: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:18: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
+ ./configure --prefix=/usr/ --sysconfdir=/etc/ --disable-nls
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking whether NLS is requested... no
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking whether to use NLS... no
checking for nanosleep in -lrt... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking utmp.h usability... yes
checking utmp.h presence... yes
checking for utmp.h... yes
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking for pid_t... yes
checking for size_t... yes
checking for uid_t in sys/types.h... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working strnlen... yes
checking for alarm... yes
checking for bzero... yes
checking for clock_gettime... yes
checking for getpass... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memset... yes
checking for select... yes
checking for setenv... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for sysinfo... yes
checking for uname... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config/Makefile
config.status: creating po/Makefile.in
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
+ DESTDIR=/build/destdir/
+ make all install
Making all in src
make[1]: Entering directory `/build/MAC-Telnet/src'
make  all-am
make[2]: Entering directory `/build/MAC-Telnet/src'
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-mactelnet.o -MD -MP -MF .deps/mactelnet-mactelnet.Tpo -c -o mactelnet-mactelnet.o `test -f 'mactelnet.c' || echo './'`mactelnet.c
mv -f .deps/mactelnet-mactelnet.Tpo .deps/mactelnet-mactelnet.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-protocol.o -MD -MP -MF .deps/mactelnet-protocol.Tpo -c -o mactelnet-protocol.o `test -f 'protocol.c' || echo './'`protocol.c
mv -f .deps/mactelnet-protocol.Tpo .deps/mactelnet-protocol.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-console.o -MD -MP -MF .deps/mactelnet-console.Tpo -c -o mactelnet-console.o `test -f 'console.c' || echo './'`console.c
mv -f .deps/mactelnet-console.Tpo .deps/mactelnet-console.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-interfaces.o -MD -MP -MF .deps/mactelnet-interfaces.Tpo -c -o mactelnet-interfaces.o `test -f 'interfaces.c' || echo './'`interfaces.c
mv -f .deps/mactelnet-interfaces.Tpo .deps/mactelnet-interfaces.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-md5.o -MD -MP -MF .deps/mactelnet-md5.Tpo -c -o mactelnet-md5.o `test -f 'md5.c' || echo './'`md5.c
mv -f .deps/mactelnet-md5.Tpo .deps/mactelnet-md5.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-mndp.o -MD -MP -MF .deps/mactelnet-mndp.Tpo -c -o mactelnet-mndp.o `test -f 'mndp.c' || echo './'`mndp.c
mv -f .deps/mactelnet-mndp.Tpo .deps/mactelnet-mndp.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DFROM_MACTELNET -g -O2 -MT mactelnet-autologin.o -MD -MP -MF .deps/mactelnet-autologin.Tpo -c -o mactelnet-autologin.o `test -f 'autologin.c' || echo './'`autologin.c
mv -f .deps/mactelnet-autologin.Tpo .deps/mactelnet-autologin.Po
gcc -DFROM_MACTELNET -g -O2   -o mactelnet mactelnet-mactelnet.o mactelnet-protocol.o mactelnet-console.o mactelnet-interfaces.o mactelnet-md5.o mactelnet-mndp.o mactelnet-autologin.o  -lrt
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'    -g -O2 -MT macping.o -MD -MP -MF .deps/macping.Tpo -c -o macping.o macping.c
mv -f .deps/macping.Tpo .deps/macping.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'    -g -O2 -MT interfaces.o -MD -MP -MF .deps/interfaces.Tpo -c -o interfaces.o interfaces.c
mv -f .deps/interfaces.Tpo .deps/interfaces.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'    -g -O2 -MT protocol.o -MD -MP -MF .deps/protocol.Tpo -c -o protocol.o protocol.c
mv -f .deps/protocol.Tpo .deps/protocol.Po
gcc  -g -O2   -o macping macping.o interfaces.o protocol.o  -lrt
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'    -g -O2 -MT mndp.o -MD -MP -MF .deps/mndp.Tpo -c -o mndp.o mndp.c
mv -f .deps/mndp.Tpo .deps/mndp.Po
gcc  -g -O2   -o mndp mndp.o protocol.o  -lrt
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-mactelnetd.o -MD -MP -MF .deps/mactelnetd-mactelnetd.Tpo -c -o mactelnetd-mactelnetd.o `test -f 'mactelnetd.c' || echo './'`mactelnetd.c
mactelnetd.c: In function ‘user_login’:
mactelnetd.c:454:3: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
   abort_connection(curconn, pkthdr, _("Login failed, incorrect username or password\r\n"));
   ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:471:4: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
    abort_connection(curconn, pkthdr, _("Terminal error\r\n"));
    ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:487:4: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
    abort_connection(curconn, pkthdr, _("System error, out of memory\r\n"));
    ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:495:4: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
    abort_connection(curconn, pkthdr, _("System error, out of memory\r\n"));
    ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:502:4: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
    abort_connection(curconn, pkthdr, _("Local user not accessible\r\n"));
    ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:515:4: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
    abort_connection(curconn, pkthdr, _("Error opening terminal\r\n"));
    ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c:563:5: warning: passing argument 3 of ‘abort_connection’ discards ‘const’ qualifier from pointer target type [enabled by default]
     abort_connection(curconn, pkthdr, _("Internal error\r\n"));
     ^
mactelnetd.c:392:13: note: expected ‘char *’ but argument is of type ‘const char *’
 static void abort_connection(struct mt_connection *curconn, struct mt_mactelnet_hdr *pkthdr, char *message) {
             ^
mactelnetd.c: In function ‘sigterm_handler’:
mactelnetd.c:888:4: warning: passing argument 3 of ‘add_control_packet’ discards ‘const’ qualifier from pointer target type [enabled by default]
    add_control_packet(&pdata, MT_CPTYPE_PLAINDATA, _(message), strlen(_(message)));
    ^
In file included from mactelnetd.c:79:0:
protocol.h:126:12: note: expected ‘void *’ but argument is of type ‘const char *’
 extern int add_control_packet(struct mt_packet *packet, enum mt_cptype cptype, void *cpdata, unsigned short data_len);
            ^
mactelnetd.c: In function ‘main’:
mactelnetd.c:1210:6: warning: passing argument 3 of ‘add_control_packet’ discards ‘const’ qualifier from pointer target type [enabled by default]
      add_control_packet(&pdata, MT_CPTYPE_PLAINDATA, _("Timeout\r\n"), 9);
      ^
In file included from mactelnetd.c:79:0:
protocol.h:126:12: note: expected ‘void *’ but argument is of type ‘const char *’
 extern int add_control_packet(struct mt_packet *packet, enum mt_cptype cptype, void *cpdata, unsigned short data_len);
            ^
mv -f .deps/mactelnetd-mactelnetd.Tpo .deps/mactelnetd-mactelnetd.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-protocol.o -MD -MP -MF .deps/mactelnetd-protocol.Tpo -c -o mactelnetd-protocol.o `test -f 'protocol.c' || echo './'`protocol.c
mv -f .deps/mactelnetd-protocol.Tpo .deps/mactelnetd-protocol.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-interfaces.o -MD -MP -MF .deps/mactelnetd-interfaces.Tpo -c -o mactelnetd-interfaces.o `test -f 'interfaces.c' || echo './'`interfaces.c
mv -f .deps/mactelnetd-interfaces.Tpo .deps/mactelnetd-interfaces.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-console.o -MD -MP -MF .deps/mactelnetd-console.Tpo -c -o mactelnetd-console.o `test -f 'console.c' || echo './'`console.c
mv -f .deps/mactelnetd-console.Tpo .deps/mactelnetd-console.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-users.o -MD -MP -MF .deps/mactelnetd-users.Tpo -c -o mactelnetd-users.o `test -f 'users.c' || echo './'`users.c
mv -f .deps/mactelnetd-users.Tpo .deps/mactelnetd-users.Po
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR='"/usr/share/locale"'   -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2 -MT mactelnetd-md5.o -MD -MP -MF .deps/mactelnetd-md5.Tpo -c -o mactelnetd-md5.o `test -f 'md5.c' || echo './'`md5.c
mv -f .deps/mactelnetd-md5.Tpo .deps/mactelnetd-md5.Po
gcc -DUSERSFILE='"/etc/mactelnetd.users"' -g -O2   -o mactelnetd mactelnetd-mactelnetd.o mactelnetd-protocol.o mactelnetd-interfaces.o mactelnetd-console.o mactelnetd-users.o mactelnetd-md5.o  -lrt
make[2]: Leaving directory `/build/MAC-Telnet/src'
make[1]: Leaving directory `/build/MAC-Telnet/src'
Making all in doc
make[1]: Entering directory `/build/MAC-Telnet/doc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/build/MAC-Telnet/doc'
Making all in config
make[1]: Entering directory `/build/MAC-Telnet/config'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/build/MAC-Telnet/config'
Making all in po
make[1]: Entering directory `/build/MAC-Telnet/po'
make[1]: Leaving directory `/build/MAC-Telnet/po'
make[1]: Entering directory `/build/MAC-Telnet'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/build/MAC-Telnet'
Making install in src
make[1]: Entering directory `/build/MAC-Telnet/src'
make[2]: Entering directory `/build/MAC-Telnet/src'
 /usr/bin/mkdir -p '/build/destdir//usr/bin'
  /usr/bin/install -c mactelnet macping mndp '/build/destdir//usr/bin'
 /usr/bin/mkdir -p '/build/destdir//usr/sbin'
  /usr/bin/install -c mactelnetd '/build/destdir//usr/sbin'
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/build/MAC-Telnet/src'
make[1]: Leaving directory `/build/MAC-Telnet/src'
Making install in doc
make[1]: Entering directory `/build/MAC-Telnet/doc'
make[2]: Entering directory `/build/MAC-Telnet/doc'
make[2]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '/build/destdir//usr/share/man/man1'
 /usr/bin/install -c -m 644 mactelnet.1 mactelnetd.1 mndp.1 macping.1 '/build/destdir//usr/share/man/man1'
make[2]: Leaving directory `/build/MAC-Telnet/doc'
make[1]: Leaving directory `/build/MAC-Telnet/doc'
Making install in config
make[1]: Entering directory `/build/MAC-Telnet/config'
make[2]: Entering directory `/build/MAC-Telnet/config'
 /usr/bin/mkdir -p '/build/destdir//etc'
 /usr/bin/install -c -m 644 mactelnetd.users '/build/destdir//etc'
make  install-exec-hook
make[3]: Entering directory `/build/MAC-Telnet/config'
chmod 600 /build/destdir//etc/mactelnetd.users
chown root /build/destdir//etc/mactelnetd.users
make[3]: Leaving directory `/build/MAC-Telnet/config'
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/build/MAC-Telnet/config'
make[1]: Leaving directory `/build/MAC-Telnet/config'
Making install in po
make[1]: Entering directory `/build/MAC-Telnet/po'
if test "mactelnet" = "gettext-tools"; then \
  /usr/bin/mkdir -p /build/destdir//usr/share/gettext/po; \
  for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
    /usr/bin/install -c -m 644 ./$file \
                    /build/destdir//usr/share/gettext/po/$file; \
  done; \
  for file in Makevars; do \
    rm -f /build/destdir//usr/share/gettext/po/$file; \
  done; \
else \
  : ; \
fi
make[1]: Leaving directory `/build/MAC-Telnet/po'
make[1]: Entering directory `/build/MAC-Telnet'
make[2]: Entering directory `/build/MAC-Telnet'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/build/MAC-Telnet'
make[1]: Leaving directory `/build/MAC-Telnet'
```
Maybe The errors are the cause?

**Comment by elico** [comment]
The RPM build sources at:
http://gogs.ngtech.co.il/elicro/MAC-Telnet-CentOS7-RPM-Build

And Repository is at:
http://ngtech.co.il/repo/centos/7/x86_64/

Files:
http://ngtech.co.il/repo/centos/7/x86_64/mactelnetd-0.4.4-2.el7.centos.x86_64.rpm
http://ngtech.co.il/repo/centos/7/x86_64/mactelnetd-0.4.4-2.el7.centos.x86_64.rpm

**Comment by antwal** [comment]
Hi, the link [http://gogs.ngtech.co.il/elicro/MAC-Telnet-CentOS7-RPM-Build](http://gogs.ngtech.co.il/elicro/MAC-Telnet-CentOS7-RPM-Build) not working

**Comment by elico** [comment]
@antwal Thanks.
